export const SET_SORT_BY = "FILTER/SET_SORT_BY";
export const SET_CATEGORY = "FILTER/SET_CATEGORY";

export const CLEAR_CART = "CART/CLEAR_CART";
export const PLUS_CART_ITEM = "CART/PLUS_CART_ITEM";
export const ADD_PIZZA_CART = "CART/ADD_PIZZA_CART";
export const MINUS_CART_ITEM = "CART/MINUS_CART_ITEM";
export const REMOVE_CART_ITEM = "CART/REMOVE_CART_ITEM";

export const SET_LOADED = "SET_LOADED";
export const SET_PIZZAS = "SET_PIZZAS";